name: calculator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  ant_icons: ^2.0.0-nullsafety.0
  evil_icons_flutter: ^0.5.0
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  heroicons: ^0.9.0
  line_awesome_flutter: ^2.0.0
  math_expressions: ^2.4.0
  mdi: ^5.0.0-nullsafety.0
  rename: ^3.0.1
  shared_preferences: ^2.2.2
  unicons: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/appIcon.png"

flutter:
  uses-material-design: true
  assets:
  - assets/svg/historyDelete.svg
  - assets/svg/calculatorFilled.svg
  - assets/svg/calculatorOutlined.svg
  - assets/svg/converterFilled.svg
  - assets/svg/converterOutlined.svg
  - assets/svg/currencyOutlined.svg
  - assets/svg/currencyFilled.svg
  - assets/svg/cake.svg

  - assets/svg/units/acceleration.svg
  - assets/svg/units/angle.svg
  - assets/svg/units/area.svg
  - assets/svg/units/density.svg
  - assets/svg/units/digitalData.svg
  - assets/svg/units/electricCharge.svg
  - assets/svg/units/energy.svg
  - assets/svg/units/force.svg
  - assets/svg/units/frequency.svg
  - assets/svg/units/fuelConsumption.svg
  - assets/svg/units/illuminance.svg
  - assets/svg/units/molarMass.svg
  - assets/svg/units/molarVolume.svg
  - assets/svg/units/power.svg
  - assets/svg/units/pressure.svg
  - assets/svg/units/torque.svg
