name: calculator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  line_awesome_flutter: ^2.0.0
  rename: ^3.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/appIcon.png"

flutter:
  uses-material-design: true
  assets:
  - assets/svg/xPower2.svg
  - assets/svg/factorial.svg
  - assets/svg/squareRoot.svg
